FROM arm64v8/ubuntu:22.04
LABEL maintainer="asoragna at irobot dot com"

RUN apt-get update && apt-get install -y \
    libacl1-dev \
    libc6-dev \
    libeigen3-dev \
    libpthread-stubs0-dev \
    libtinyxml2-dev \
    python3-dev \
    python3-numpy

